up

diff --git a/frontend/dockerfile b/frontend/dockerfile
--- a/frontend/dockerfile
+++ b/frontend/dockerfile
@@ -16,13 +16,13 @@ RUN npm install
 # Copy everything from the current directory
 COPY . .
 
-# Check if necessary files/folders exist after copy
-RUN if [ ! -d .next ]; then echo ".next directory not found!"; exit 1; fi
 
 # Build the application
 RUN npm run build
 
 # Ensure that the build output directory is created
+# Check if necessary files/folders exist after copy
+RUN if [ ! -d .next ]; then echo ".next directory not found!"; exit 1; fi
 RUN ls -la .next
 
 # Expose the port the app runs on
